In [1]:
import numpy as np
from scipy import linalg #linear algorithms
import scipy as sp

In [2]:
a=np.array([[3,5],[2,-1]])
b=np.array([[2],[4]])
x=linalg.solve(a,b)
print(x)

[[ 1.69230769]
 [-0.61538462]]


In [3]:
a=np.array([[3,2,-5],[1,-2,3],[4,1,3]])
b=np.array([[2],[4],[-1]])
x=linalg.solve(a,b)
print(x)

[[ 1.07407407]
 [-2.74074074]
 [-0.85185185]]


In [5]:
a=np.array([[3,2,-5],[1,6,-5]])
b=np.array([[2],[6]])
x=linalg.lstsq(a,b)
x

(array([[-0.26455026],
        [ 0.86772487],
        [-0.21164021]]),
 array([], dtype=float64),
 2,
 array([9.57920801, 2.87032646]))

In [8]:
a=np.array([[3,2,-5],[1,6,-5]])
b=np.array([[2],[6]])
x=linalg.lstsq(a,b)
x,resid,rank,sigma=linalg.lstsq(a,b)
print(x)

[[-0.26455026]
 [ 0.86772487]
 [-0.21164021]]


In [10]:
a=np.array([[3,2],[3,-7]])

print(linalg.inv(a)) #inverse of a,when matrix is square

print(linalg.det(a))  #determinant

print(linalg.pinv(a))   #inverse of a when matrix is not square


[[ 0.25925926  0.07407407]
 [ 0.11111111 -0.11111111]]
-27.0
[[ 0.25925926  0.07407407]
 [ 0.11111111 -0.11111111]]


In [11]:
a=np.array([3,-4,5])
print(linalg.norm(a)) # L2 norm of a matrix


7.0710678118654755


In [12]:
print(linalg.norm(a,1))  # L1 norm


12.0


In [13]:
print(linalg.norm(a,np.inf))  # L infinity norm


5.0
